[package]
name = "live-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html_editor = "0.1.0"
notify = "4.0.17"
tide = "0.16.0"
async-std = { version = "1.10.0", features = ["attributes"] }
tide-websockets = "0.4.0"
once_cell = "1.9.0"
uuid = { version = "0.8.2", features = ["v4"] }
clap = { version = "3.0.7", features = ["derive"] }
